In [1]:
import pandas as pd

data = {
    '이름': ['철수','영희','민수','지영','수진'],
    '성별': ['남성','여성','남성','여성','여성'],
    '등급': ['B','A','C','C','B'],
    '지역': ['서울','부산','서울','대구','부산']
}
df=pd.DataFrame(data)
df

   이름  성별 등급  지역
0  철수  남성  B  서울
1  영희  여성  A  부산
2  민수  남성  C  서울
3  지영  여성  C  대구
4  수진  여성  B  부산

In [2]:
gender_dummy = pd.get_dummies(df['성별'], prefix='성별')
gender_dummy

   성별_남성  성별_여성
0   True  False
1  False   True
2   True  False
3  False   True
4  False   True

In [3]:
grade_dummy = pd.get_dummies(df['등급'], prefix='등급')
region_dummy = pd.get_dummies(df['지역'], prefix='지역')
#기존데이터 + 더미변수 결합
df_dummy = pd.concat([df, gender_dummy, grade_dummy, region_dummy], axis=1) #axis=1 가로방향
df_dummy

   이름  성별 등급  지역  성별_남성  성별_여성   등급_A   등급_B   등급_C  지역_대구  지역_부산  지역_서울
0  철수  남성  B  서울   True  False  False   True  False  False  False   True
1  영희  여성  A  부산  False   True   True  False  False  False   True  False
2  민수  남성  C  서울   True  False  False  False   True  False  False   True
3  지영  여성  C  대구  False   True  False  False   True   True  False  False
4  수진  여성  B  부산  False   True  False   True  False  False   True  False

In [4]:
df_dummy = df_dummy.drop(columns=['성별','등급','지역'])
df_dummy

   이름  성별_남성  성별_여성   등급_A   등급_B   등급_C  지역_대구  지역_부산  지역_서울
0  철수   True  False  False   True  False  False  False   True
1  영희  False   True   True  False  False  False   True  False
2  민수   True  False  False  False   True  False  False   True
3  지영  False   True  False  False   True   True  False  False
4  수진  False   True  False   True  False  False   True  False