In [1]:
import pandas as pd
import statsmodels.api as sm

df = pd.DataFrame({
    'y': [29,33,37,41,45,49,54,58,62,66,71,75],
    'x1': [2,3,4,5,6,7,8,9,10,11,12,13],
    'x2': [2,3,4,5,6,7,8,9,10,11,12,14],
    'x3': [5,4,6,5,7,6,5,7,6,8,7,6]
})
df

     y  x1  x2  x3
0   29   2   2   5
1   33   3   3   4
2   37   4   4   6
3   41   5   5   5
4   45   6   6   7
5   49   7   7   6
6   54   8   8   5
7   58   9   9   7
8   62  10  10   6
9   66  11  11   8
10  71  12  12   7
11  75  13  14   6

In [2]:
df[['x1','x2']].corr()

          x1        x2
x1  1.000000  0.997722
x2  0.997722  1.000000

In [3]:
X = df[['x1','x2','x3']]
y = df['y']

In [4]:
result = sm.OLS(y,X).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.996
Model:                            OLS   Adj. R-squared (uncentered):              0.995
Method:                 Least Squares   F-statistic:                              730.9
Date:                Thu, 15 Jan 2026   Prob (F-statistic):                    4.61e-11
Time:                        12:42:25   Log-Likelihood:                         -31.821
No. Observations:                  12   AIC:                                      69.64
Df Residuals:                       9   BIC:                                      71.10
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.8513      5.350     -0.159      0.877     -12.953      11.251
x2             4.4531      5.048      0.882      0.401      -6.967      15.873
x3             3.9540      0.626      6.316      0.000       2.538       5.370
==============================================================================
Omnibus:                        0.064   Durbin-Watson:                   2.539
Prob(Omnibus):                  0.968   Jarque-Bera (JB):                0.295
Skew:                           0.011   Prob(JB):                        0.863
Kurtosis:                       2.232   Cond. No.                         84.4
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [5]:
X2 = df[['x1','x3']]
result2 = sm.OLS(y,X2).fit()
result2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.996
Model:                            OLS   Adj. R-squared (uncentered):              0.995
Method:                 Least Squares   F-statistic:                              1121.
Date:                Thu, 15 Jan 2026   Prob (F-statistic):                    1.73e-12
Time:                        12:42:25   Log-Likelihood:                         -32.319
No. Observations:                  12   AIC:                                      68.64
Df Residuals:                      10   BIC:                                      69.61
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             3.8539      0.403      9.570      0.000       2.957       4.751
x3             3.6927      0.545      6.771      0.000       2.478       4.908
==============================================================================
Omnibus:                        0.164   Durbin-Watson:                   2.151
Prob(Omnibus):                  0.921   Jarque-Bera (JB):                0.355
Skew:                          -0.157   Prob(JB):                        0.837
Kurtosis:                       2.217   Cond. No.                         5.99
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""