In [1]:
import pandas as pd

df = pd.read_csv('c:/data/insta/insta_test.csv')
df.head()

,user_id,app_name,age,gender,country,income_level,employment_status,exercise_hours_per_week,sleep_hours_per_night,perceived_stress_score,...,dms_sent_per_week,dms_received_per_week,ads_viewed_per_day,ads_clicked_per_day,time_on_feed_per_day,time_on_explore_per_day,time_on_messages_per_day,time_on_reels_per_day,followers_count,following_count
0,1,Instagram,51,Female,India,High,Retired,7.2,7.7,3,...,12,12,4,1,2,1,1,2,374,647
1,2,Instagram,64,Female,United Kingdom,Middle,Full-time employed,10.9,8.6,1,...,18,10,11,1,31,19,16,19,2585,3511
2,3,Instagram,41,Female,Canada,Middle,Student,5.0,6.7,4,...,12,13,4,0,3,1,1,1,3414,6761
3,4,Instagram,27,Non-binary,South Korea,Middle,Unemployed,10.6,6.5,18,...,31,32,33,3,108,64,52,64,617,1193
4,5,Instagram,55,Male,India,Upper-middle,Full-time employed,7.7,6.8,19,...,29,37,20,5,78,55,22,55,1157,1072

In [13]:
#더미변수
gender_dummy = pd.get_dummies(df['gender'], prefix='gender')
income_level_dummy = pd.get_dummies(df['income_level'], prefix='income')
employment_status_dummy = pd.get_dummies(df['employment_status'],prefix='emp')
df_dummy = pd.concat([df, gender_dummy, income_level_dummy, employment_status_dummy], axis=1)
df_dummy = df_dummy.drop(columns=['user_id','app_name','country','gender', 'income_level', 'employment_status'])
df_dummy.head()

,age,exercise_hours_per_week,sleep_hours_per_night,perceived_stress_score,self_reported_happiness,daily_steps_count,weekly_work_hours,daily_active_minutes_instagram,sessions_per_day,posts_created_per_week,...,income_High,income_Low,income_Lower-middle,income_Middle,income_Upper-middle,emp_Freelancer,emp_Full-time employed,emp_Retired,emp_Student,emp_Unemployed
0,51,7.2,7.7,3,8,8107,49.9,5,1,3,...,True,False,False,False,False,False,False,True,False,False
1,64,10.9,8.6,1,1,8059,15.6,74,5,3,...,False,False,False,True,False,False,True,False,False,False
2,41,5.0,6.7,4,10,7872,31.8,5,1,7,...,False,False,False,True,False,False,False,False,True,False
3,27,10.6,6.5,18,1,7801,43.4,233,9,5,...,False,False,False,True,False,False,False,False,False,True
4,55,7.7,6.8,19,1,8005,50.2,184,14,5,...,False,False,False,False,True,False,True,False,False,False

In [ ]:
#스케일링