In [3]:
import pandas as pd
import numpy as np

df1 = pd.read_csv('c:/data/ontime/2006.csv')
df2 = pd.read_csv('c:/data/ontime/2007.csv')
df3 = pd.read_csv('c:/data/ontime/2008.csv')
df1=pd.concat([df1, df2, df3])

In [4]:
df1.shape

(16984354, 29)

In [6]:
df1.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [9]:
df2 = df1[['Year','Month','ArrDelay','DepDelay']]
df2.head()

   Year  Month  ArrDelay  DepDelay
0  2006      1       6.0      -2.0
1  2006      1      -5.0       0.0
2  2006      1     -23.0       0.0
3  2006      1      -8.0      -2.0
4  2006      1       0.0      -8.0

In [11]:
df2.tail()

         Year  Month  ArrDelay  DepDelay
2389212  2008      4      -3.0       0.0
2389213  2008      4       3.0      -1.0
2389214  2008      4       3.0       0.0
2389215  2008      4      -1.0      -2.0
2389216  2008      4      -2.0       6.0

In [13]:
df2.shape

(16984354, 4)

In [15]:
df2 = df2.dropna(how='any')

In [17]:
df2.shape

(16598211, 4)

In [19]:
result = df2.groupby(['Year','Month'], as_index=False).count()
result.head()

   Year  Month  ArrDelay  DepDelay
0  2006      1    570130    570130
1  2006      2    518645    518645
2  2006      3    596578    596578
3  2006      4    577718    577718
4  2006      5    594626    594626

In [21]:
result.to_csv('c:/data/ontime/result.csv')

In [29]:
from sqlalchemy import create_engine

engine = create_engine(
    'mysql+pymysql://user:1234@localhost:3306/ontime'
)
result.to_sql(
    name='ontime_result',
    con=engine,
    if_exists='replace',
    index=False
)

28