In [1]:
import pandas as pd

df=pd.read_csv("c:/data/rides/rides.csv")
df.head()

  weekend  num.child    distance  rides  games  wait  clean  overall
0     yes          0  114.648259     87     73    60     89       47
1     yes          2   27.014097     87     78    76     87       65
2      no          1   63.300975     85     80    70     88       61
3     yes          0   25.909931     88     72    66     89       37
4      no          4   54.718307     84     87    74     87       68

In [2]:
df2 = pd.get_dummies(df['weekend'], prefix='weekend', dtype=int)
df = pd.concat([df,df2], axis=1)
del df['weekend']
df.head()

,num.child,distance,rides,games,wait,clean,overall,weekend_no,weekend_yes
0,0,114.648259,87,73,60,89,47,0,1
1,2,27.014097,87,78,76,87,65,0,1
2,1,63.300975,85,80,70,88,61,1,0
3,0,25.909931,88,72,66,89,37,0,1
4,4,54.718307,84,87,74,87,68,1,0

In [3]:
df.columns

Index(['num.child', 'distance', 'rides', 'games', 'wait', 'clean', 'overall',
       'weekend_no', 'weekend_yes'],
      dtype='object')

In [4]:
X = df[['num.child', 'distance', 'rides', 'games', 'wait', 'clean', 'weekend_no', 'weekend_yes']]
y = df['overall']

In [5]:
import statsmodels.api as sm

model = sm.OLS(y,X)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                overall   R-squared:                       0.683
Model:                            OLS   Adj. R-squared:                  0.679
Method:                 Least Squares   F-statistic:                     151.6
Date:                Mon, 19 Jan 2026   Prob (F-statistic):          1.73e-118
Time:                        10:27:26   Log-Likelihood:                -1804.1
No. Observations:                 500   AIC:                             3624.
Df Residuals:                     492   BIC:                             3658.
Df Model:                           7
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
num.child       3.6160      0.270     13.403      0.000       3.086       4.146
distance        0.0449      0.012      3.686      0.000       0.021       0.069
rides           0.6136      0.121      5.072      0.000       0.376       0.851
games           0.1383      0.059      2.356      0.019       0.023       0.254
wait            0.5648      0.041     13.896      0.000       0.485       0.645
clean           0.9272      0.136      6.821      0.000       0.660       1.194
weekend_no   -140.6125      7.154    -19.655      0.000    -154.669    -126.556
weekend_yes  -141.3283      7.121    -19.847      0.000    -155.319    -127.337
==============================================================================
Omnibus:                        2.188   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.335   Jarque-Bera (JB):                1.943
Skew:                          -0.050   Prob(JB):                        0.379
Kurtosis:                       2.712   Cond. No.                     4.14e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.14e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [10]:
result.predict([2,20,80,70,80,90,0,1])

array([54.20768166])

In [11]:
result.predict([3,10,80,70,80,90,1,0])

array([58.09006564])

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)
model = LinearRegression().fit(X_train, y_train)

In [9]:
print('학습용:',model.score(X_train, y_train))
print('검증용:',model.score(X_test, y_test))

학습용: 0.6670609590984946
검증용: 0.7212343349658575

In [13]:
model.predict([[2,20,80,70,80,90,0,1]])

C:\python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53.30062057])

In [14]:
model.predict([[3,10,80,70,80,90,1,0]])

C:\python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([57.97589809])

In [15]:
import joblib
joblib.dump(model, 'c:/data/rides/rides_regression.model')

['c:/data/rides/rides_regression.model']

In [1]:
import joblib
model = joblib.load('c:/data/rides/rides_regression.model')

In [2]:
model.predict([[2,20,80,70,80,90,0,1]])

C:\python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53.30062057])

In [3]:
model.predict([[3,10,80,70,80,90,1,0]])

C:\python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([57.97589809])